### ISSUE TITLE
npm i -g wasmedge-core didn't work on MacOS

### ISSUE THREAD

**Issue by katopz** [second-state/wasmedge-core#16]
```shell
$ npm i -g wasmedge-core
npm ERR! code 127
npm ERR! path /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core
npm ERR! command failed
npm ERR! command sh -c ./scripts/preinstall.sh
npm ERR! ./scripts/preinstall.sh: line 16: wget: command not found
```

Any workaround?

**Comment by juntao** [comment]
You need to install `wget` first.

https://www.fossmint.com/install-and-use-wget-on-mac/

**Comment by katopz** [comment]
Thanks, I did
```shell
brew install wget
```
and then
```shell
$ npm i -g wasmedge-core
npm ERR! code 1
npm ERR! path /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core
npm ERR! command failed
npm ERR! command sh -c ./scripts/preinstall.sh
npm ERR! Uninstall script checksum mismatch
npm ERR! --2022-02-20 16:34:55--  https://raw.githubusercontent.com/WasmEdge/WasmEdge/0.9.0/utils/uninstall.sh
npm ERR! Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
npm ERR! Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
npm ERR! HTTP request sent, awaiting response... 200 OK
npm ERR! Length: 6484 (6.3K) [text/plain]
npm ERR! Saving to: ‘/tmp/uninstall_wasmedge.sh’
npm ERR! 
npm ERR!      0K ......                                                100% 31.9M=0s
npm ERR! 
npm ERR! 2022-02-20 16:34:55 (31.9 MB/s) - ‘/tmp/uninstall_wasmedge.sh’ saved [6484/6484]
npm ERR! 
npm ERR! ./scripts/preinstall.sh: line 17: sha1sum: command not found
```

So I try
```shell
brew install md5sha1sum
```

And then
```shell
$ npm i -g wasmedge-core
npm ERR! code 1
npm ERR! path /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/wasmedge/src/addon.o
npm ERR! Failed to execute '/Users/katopz/.nvm/versions/node/v16.13.0/bin/node /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64/wasmedge.node --module_name=wasmedge --module_path=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! node-pre-gyp info using node@16.13.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64/wasmedge.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/second-state/wasmedge-core/releases/download/0.9.0/wasmedge-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/second-state/wasmedge-core/releases/download/0.9.0/wasmedge-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for wasmedge-core@0.9.0 and node@16.13.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/second-state/wasmedge-core/releases/download/0.9.0/wasmedge-darwin-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.10 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/katopz/Library/Caches/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/katopz/Library/Caches/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/katopz/Library/Caches/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/addon.cc:1:
npm ERR! In file included from ../src/wasmedgeaddon.h:5:
npm ERR! ../src/cache.h:8:10: fatal error: 'boost/functional/hash.hpp' file not found
npm ERR! #include <boost/functional/hash.hpp>
npm ERR!          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/wasmedge/src/addon.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/Users/katopz/.nvm/versions/node/v16.13.0/bin/node" "/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64/wasmedge.node" "--module_name=wasmedge" "--module_path=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/katopz/.nvm/versions/node/v16.13.0/bin/node /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64/wasmedge.node --module_name=wasmedge --module_path=/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/lib/binding/darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 19.6.0
npm ERR! node-pre-gyp ERR! command "/Users/katopz/.nvm/versions/node/v16.13.0/bin/node" "/Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/katopz/.nvm/versions/node/v16.13.0/lib/node_modules/wasmedge-core
npm ERR! node-pre-gyp ERR! node -v v16.13.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! node-pre-gyp ERR! not ok
```

🤔

**Comment by katopz** [comment]
Oh, I just realize that it has to build from the source. So I will need to install [packages](https://github.com/second-state/wasmedge-core#development-requirements) at step 2 first. 

But I just want to run this example and it yelling for `wasm-core` https://github.com/second-state/wasm-learning/blob/master/nodejs/email/README.md (and that's why i'm here)

I think I will try to do it in docker instead. I don't want to mess up my machine.

Thanks anyway.
